### ISSUE TITLE
[URGENT] Can't hydrate my object

### ISSUE THREAD

**Issue by onishinji** [steevanb/doctrine-read-only-hydrator#1]
I have an object (Stay) which have some relations (Client, ..) when i use ->leftJoin('stay.client', 'client') with an Stay not yet linked to Client => Fatal Error: Argument 2 passed to steevanb\\DoctrineReadOnlyHydrator\\Hydrator\\SimpleObjectHydrator::doHydrateRowData() must be of the type array, null given, called in /home/huttopia/Public/api/vendor/composer/steevanb/doctrine-read-only-hydrator/Hydrator/SimpleObjectHydrator.php on line 187 and defined in /home/huttopia/Public/api/vendor/composer/steevanb/doctrine-read-only-hydrator/Hydrator/SimpleObjectHydrator.php (line 61)

**Comment by steevanb** [comment]
Thanks for the report, it's fixed in 2.0.4 !
