### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by Perni1984** [steevanb/doctrine-read-only-hydrator#14]
Hi, I am very interested in using the read only hydrator. Unfortunately I cannot find a license statement anywhere in the repo. Could you kindly clarify under which license this code is released?

**Comment by steevanb** [comment]
Hi, my bad for the late...

I never add license in my repositories, so you can use it for free in your project, fork it and modify what you need.

**Comment by wsldankers** [comment]
Please be aware that people are legally prohibited from using your software unless you license it. That's how current copyright law works, as unfortunate as it may be. Simply adding a standard license (like MIT or GPL) should be enough.

**Comment by steevanb** [comment]
License under GNU had been added 👍
