### ISSUE TITLE
Fatal error on partial load

### ISSUE THREAD

**Issue by acoquoin** [steevanb/doctrine-read-only-hydrator#9]
`Type error: Argument 2 passed to ComposerOverloadClass\steevanb\DoctrineReadOnlyHydrator\Hydrator\SimpleObjectHydrator::doHydrateRowData() must be of the type array, null given, called in /home/huttopia/Desktop/huttosoftv2-back/var/ComposerOverloadClass/steevanb/DoctrineReadOnlyHydrator/Hydrator/SimpleObjectHydrator.php on line 201`

Hi @steevanb  :stuck_out_tongue: 
We have a problem on partialLoad ($doctrine->getpartialQuery()>getResult(ReadOnlyHydrator::HYDRATOR_NAME)), seems pretty random, i think i a problem when the proxy class is generated.

Have you saw this problem before ?
Thanks dude !

**Comment by steevanb** [comment]
I think it's ok since mars ?
